include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart, app/**.g.dart, packages/**.g.dart, packages/**/generated/**]
linter:
  rules:
    public_member_api_docs: false
    always_use_package_imports: false
    flutter_style_todos: false
