name: {{app_name.snakeCase()}}_workspace
sdkPath: .fvm/flutter_sdk

packages:
  - app
  - packages/*

scripts:
  analyze:
    exec: fvm dart analyze .

  format:
    exec: fvm dart fix ./lib --apply && fvm dart format ./lib

  generate:
    run: fvm dart run build_runner build --delete-conflicting-outputs
    exec: 
      concurrency: 1
      orderDependents: true
    description: Build all generated files for Dart & Flutter packages in this project.
    packageFilters:
      dependsOn: build_runner
